---
- name: Pull Docker Image of Scientific Calculator
  hosts: all
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Pull docker image
    docker_image:
      name: khaveesh/scientific-calculator:latest
      source: pull
